config/routes.rb
Rails.application.routes.draw do
  root 'quizzes#index'
  resources :poems, only: [:index]
  resources :quizzes
  post 'quiz', to: 'quizzes#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poem.rb
class Poem < ApplicationRecord
end

app/models/quiz.rb
class Quiz < ApplicationRecord
    before_create :level_chooser
    API = '3ed02bb8ad74f3afa33b21a3de7929f4'
    def level_chooser
      @poems = Poem.all
      case self.level
      when 1
       first_level
      end
    end

    def first_level
      @poems.each do |poem|
        if poem.context == Unicode::downcase(self.question)
          self.answer = Unicode::upcase(poem.title[0]) + poem.title.delete(poem.title[0])
          answer_sender(self.answer)
        end
      end
    end

    def answer_sender(answer)
      uri = URI("http://pushkin.rubyroidlabs.com/quiz")
      parameters = {
          answer:  answer,
          token:   API,
          task_id: self.id
        }
        Net::HTTP.post_form(uri, parameters)
        File.open('./1.txt', 'a'){ |f| f.write(parameters) }
        File.open('./1.txt', 'a'){ |f| f.write(self.question) }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    hash = JSON.parse(File.read(File.expand_path('/home/igor/pushkin-contest-bot/poems.json', __FILE__)))
    iterator = 0
    hash.each do |key, value|
      params = {:title => value , :context => key}
      @poem = Poem.new(params)
      @poem.save
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:title, :context)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new
    @quiz = Quiz.new(quiz_params)
    @quiz.save
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.permit(:question, :id, :level)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PushkinContestBot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/poems/_form.html.erb
<%= form_for(poem) do |f| %>
  <% if poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :context %>
    <%= f.text_field :context %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<h1>Editing Poem</h1>

<%= render 'form', poem: @poem %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poems</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Context</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td><%= poem.title %></td>
        <td><%= poem.context %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/poems/new.html.erb
<h1>New Poem</h1>

<%= render 'form', poem: @poem %>

<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poem.title %>
</p>

<p>
  <strong>Context:</strong>
  <%= @poem.context %>
</p>

<%= link_to 'Edit', edit_poem_path(@poem) %> |
<%= link_to 'Back', poems_path %>

app/views/quizzes/_form.html.erb
<%= form_for(quiz) do |f| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>

  <div class="field">
    <%= f.label :answer %>
    <%= f.text_field :answer %>
  </div>

  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Level</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.question %></td>
        <td><%= quiz.answer %></td>
        <td><%= quiz.level %></td>
        <td><%= quiz.id %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @quiz.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @quiz.answer %>
</p>

<p>
  <strong>Level:</strong>
  <%= @quiz.level %>
</p>

<p>
  <strong>User:</strong>
  <%= @quiz.user_id %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>